### ISSUE TITLE
Hoppers

### ISSUE THREAD

**Issue by ygtdmn** [mcmonkey4eva/monkeyslockette#1]
I can steal items with hopper. I am using 1.8 spigot protocol hack. And i am not add [Hoppers] but still i can steal.

**Comment by mcmonkey4eva** [comment]
That is weird. Sorry, I've been ignoring this project. On the off chance you still have the same setup, does that still happen? I'm pretty sure I tested that exactly that wouldn't happen at some point...

**Comment by ygtdmn** [comment]
Yes it is still same :/

**Comment by mcmonkey4eva** [comment]
As noted in the readme, `This plugin was started when I was not so great at Java or Minecraft stuff and bares some historical troubles from that.` This plugin is not really maintained or used much.
Nonetheless I've taken a vague swing at fixing this, as I've been using this plugin on an ancient server that's for whatever reason still running somehow.
