### ISSUE TITLE
Security: Chest breakin with sign placed on top

### ISSUE THREAD

**Issue by Stealthii** [mcmonkey4eva/monkeyslockette#4]
It is possible to break into someone else's locked chest by placing an additional sign on top of the lock to break it.
![Example](https://i.imgur.com/1XKOt7N.png)

**Comment by mcmonkey4eva** [comment]
As noted in the readme, `This plugin was started when I was not so great at Java or Minecraft stuff and bares some historical troubles from that.` This plugin is not really maintained or used much.
Nonetheless I've taken a vague swing at fixing this, as I've been using this plugin on an ancient server that's for whatever reason still running somehow.
